# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker:19.03.12
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          docker build https://github.com/metacall/distributable.git#master
          docker run --privileged --name tmp metacall/distributable sh -c 'guix pull'
          docker commit tmp metacall/distributable && docker rm -f tmp
          docker run -d --privileged --name tmp metacall/distributable /metacall/scripts/deps.sh
          docker commit tmp metacall/distributable && docker rm -f tmp
          docker run --rm -v $PWD/out:/metacall/pack --privileged metacall/distributable /metacall/scripts/build.sh

